/* rooms-data.js — elenco foto per camera (condiviso da tutte le lingue) */
window.ROOMS_PHOTOS = {
  "sasso-1": [
    "../img/camere/il-sasso-1-foto-01.jpg",
    "../img/camere/il-sasso-1-foto-02.jpg",
    "../img/camere/il-sasso-1-foto-03.jpg",
    "../img/camere/il-sasso-1-foto-04.jpg",
    "../img/camere/il-sasso-1-foto-05.jpg",
    "../img/camere/il-sasso-1-foto-06.jpg",
    "../img/camere/il-sasso-1-foto-07.jpg",
    "../img/camere/il-sasso-1-foto-08.jpg",
    "../img/camere/il-sasso-1-foto-09.jpg",
    "../img/camere/il-sasso-1-foto-10.jpg",
    "../img/camere/il-sasso-1-foto-11.jpg",
    "../img/camere/il-sasso-1-foto-12.jpg"
  ],
  "sasso-2": [
    "../img/camere/il-sasso-2-foto-01.jpg",
    "../img/camere/il-sasso-2-foto-02.jpg",
    "../img/camere/il-sasso-2-foto-03.jpg",
    "../img/camere/il-sasso-2-foto-04.jpg",
    "../img/camere/il-sasso-2-foto-05.jpg",
    "../img/camere/il-sasso-2-foto-06.jpg",
    "../img/camere/il-sasso-2-foto-07.jpg",
    "../img/camere/il-sasso-2-foto-08.jpg",
    "../img/camere/il-sasso-2-foto-09.jpg",
    "../img/camere/il-sasso-2-foto-10.jpg"
  ],
  "sasso-3": [
    "../img/camere/il-sasso-3-foto-01.jpg",
    "../img/camere/il-sasso-3-foto-02.jpg",
    "../img/camere/il-sasso-3-foto-03.jpg",
    "../img/camere/il-sasso-3-foto-04.jpg",
    "../img/camere/il-sasso-3-foto-05.jpg",
    "../img/camere/il-sasso-3-foto-06.jpg",
    "../img/camere/il-sasso-3-foto-07.jpg",
    "../img/camere/il-sasso-3-foto-08.jpg",
    "../img/camere/il-sasso-3-foto-09.jpg",
    "../img/camere/il-sasso-3-foto-10.jpg",
    "../img/camere/il-sasso-3-foto-11.jpg"
  ],
  "spigo-1": [
    "../img/camere/lo-spigo-1-foto-01.jpg",
    "../img/camere/lo-spigo-1-foto-02.jpg",
    "../img/camere/lo-spigo-1-foto-03.jpg",
    "../img/camere/lo-spigo-1-foto-04.jpg",
    "../img/camere/lo-spigo-1-foto-05.jpg",
    "../img/camere/lo-spigo-1-foto-06.jpg",
    "../img/camere/lo-spigo-1-foto-07.jpg",
    "../img/camere/lo-spigo-1-foto-08.jpg",
    "../img/camere/lo-spigo-1-foto-09.jpg",
    "../img/camere/lo-spigo-1-foto-10.jpg",
    "../img/camere/lo-spigo-1-foto-11.jpg",
    "../img/camere/lo-spigo-1-foto-12.jpg"
  ],
  "spigo-2": [
    "../img/camere/lo-spigo-2-foto-01.jpg",
    "../img/camere/lo-spigo-2-foto-02.jpg",
    "../img/camere/lo-spigo-2-foto-03.jpg",
    "../img/camere/lo-spigo-2-foto-04.jpg",
    "../img/camere/lo-spigo-2-foto-05.jpg",
    "../img/camere/lo-spigo-2-foto-06.jpg",
    "../img/camere/lo-spigo-2-foto-07.jpg",
    "../img/camere/lo-spigo-2-foto-08.jpg",
    "../img/camere/lo-spigo-2-foto-09.jpg",
    "../img/camere/lo-spigo-2-foto-10.jpg",
    "../img/camere/lo-spigo-2-foto-11.jpg",
    "../img/camere/lo-spigo-2-foto-12.jpg",
    "../img/camere/lo-spigo-2-foto-13.jpg"
  ],
  "spigo-3": [
    "../img/camere/lo-spigo-3-foto-01.jpg",
    "../img/camere/lo-spigo-3-foto-02.jpg",
    "../img/camere/lo-spigo-3-foto-03.jpg",
    "../img/camere/lo-spigo-3-foto-04.jpg",
    "../img/camere/lo-spigo-3-foto-05.jpg",
    "../img/camere/lo-spigo-3-foto-06.jpg",
    "../img/camere/lo-spigo-3-foto-07.jpg",
    "../img/camere/lo-spigo-3-foto-08.jpg",
    "../img/camere/lo-spigo-3-foto-09.jpg",
    "../img/camere/lo-spigo-3-foto-10.jpg",
    "../img/camere/lo-spigo-3-foto-11.jpg"
  ],
};
